stages:
  download:
    cmd: poetry run python src/creditcard_ml/scripts/download_data.py
    deps:
      - src/creditcard_ml/scripts/download_data.py
    outs:
      - data/creditcard.csv

  preprocess:
    cmd: poetry run python src/creditcard_ml/scripts/preprocess.py
    deps:
      - data/creditcard.csv
      - src/creditcard_ml/scripts/preprocess.py
    outs:
      - data/processed.csv

  train:
    cmd: poetry run train
    deps:
      - data/processed.csv
      - src/creditcard_ml/core/feature_engineering.py
      - src/creditcard_ml/training/train.py
    outs:
      - src/creditcard_ml/model/model.pkl
    metrics:
      - metrics.json:
          cache: false

  evaluate:
    cmd: poetry run python src/creditcard_ml/scripts/evaluate.py
    deps:
      - data/processed.csv
      - src/creditcard_ml/model/model.pkl
      - src/creditcard_ml/scripts/evaluate.py
    outs:
      - eval.json


